CREATE DATABASE IF NOT EXISTS SALES_DB;
CREATE SCHEMA IF NOT EXISTS SALES_DB.RAW;

USE DATABASE SALES_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS ORDERS_roshini (
    ORDER_ID NUMBER,
    CUSTOMER_NAME STRING,
    ORDER_DATE DATE,
    AMOUNT NUMBER(10,2),
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO ORDERS VALUES
(1, 'Ravi', '2025-01-01', 1200.50, CURRENT_TIMESTAMP),
(2, 'Anu',  '2025-01-02', 850.00,  CURRENT_TIMESTAMP);


select*from orders;
